version: "3.9"
services:
  unraid-dashboard:
    image: ghcr.io/<you>/unraid-dashboard:latest
    container_name: unraid-dashboard
    env_file: [.env]
    network_mode: host
    volumes:
      - ./data:/app/data
    restart: unless-stopped
